### PR TITLE
Add .net standard 2.1 in target frameworks

### PR DESCRIPTION
**Pull request by cbovar**
Hi!

* Add .net standard 2.1 in target frameworks
* Add some entries in gitignore to ignore temporary outputs

### CODE REVIEW

**Comment by kunzmi** [comment]
Hi,

the problem with netstandard2.1 is, that it doesn't support `NativeLibrary.SetDllImportResolver()` which I use to switch native library names on runtime for Linux. So of course one could compile for .netstandard2.1, but then it wouldn't run on Linux (at least not out of the box).
So in my opinion, with good old .net Framework 4 and .net core3.x on windows side and .net core3.x on Linux, one should have any possible use case, or not?

**Comment by cbovar** [comment]
Ok, I understand.

My use case is:  
(.net core app or .net framework app) --> .net standard library --> managed cuda

Some ideas:
* Throw an exception when platform is linux and _not_ .net core. I understand this would be a bit misleading for developers who will find out it doesn't work on linux only at runtime.
* I can maintain a fork of managed cuda for my app, knowing it won't work on linux, until we're all in .NET 5 (which supports  `NativeLibrary.SetDllImportResolver()`)

**Comment by kunzmi** [comment]
Well, there's even no need for a new branch, all you need is just compiling managedCuda yourself for .netstandard. I won't update the nuget packages for that because that's quite some work given the number of packages for the different libraries and I tend to mess things up doing that (I know I could automatise things more...). 
The future is pure .netCore, so just by waiting a bit the problem will be gone :)

**Comment by cbovar** [comment]
Alright.
.NET 5 should be out later this year, not so long to wait :)

**Pull request closed without merging**
