### PR TITLE
Added OpTensor for cuDNN.

### PR DESCRIPTION
**Pull request by mrakgr**
I made the OpTensor functions for the cuDNN wrapper. I should have done this 4 month ago, but I missed it by accident it seems. Well, here it is now.

Also I've noticed you did not accept the changes to the descriptions of amin, amax and such. The ones about the C vs Fortran notation. It should be C indexing notation by default. You can find the correct description in one of the previous commits on my fork.

### CODE REVIEW

**Comment by kunzmi** [comment]
I'm currently very busy with other projects... Once I'm done with the Cuda 8 update I will have a look at it!
Thanks for the contribution,
Michael

**Comment by kunzmi** [comment]
I merged it to master and also changed the CudaBLAS comments for AMIN/AMAX. Please check it... If everything is fine, I'll update the Nut package.

Thanks,
Michael

**Comment by mrakgr** [comment]
It might be partly my fault since I had difficulties with cloning the repo, but it would be good if you could undo the changes on the comments in the latest commit as now it says Fortran notation instead of the C notation. I fixed that 4 months ago and it does not seem to have been applied and then I lost the changes in the latest commit it seems. I had it right in [the old one](https://github.com/mrakgr/managedCuda/blob/ba6ec6b9dcb117ccb34d9db31b54b1a04ad3e2a8/CudaBlas/CudaBlasHandler.cs#L1163). For comparison, this is what [you have currently](https://github.com/kunzmi/managedCuda/commit/870714a785245cd418a92fe63e59e013169982d8).

**Comment by kunzmi** [comment]
Now I'm confused: you say the actual indexing is C-style 0 based, right?
I'm wondering, as e.g. on page 22 in the CUBLAS manual (chapter 2.5.2. cublasI\<t\>amin()) it sounds more like FORTRAN indexing, with 0 as an error marker...
Quick check with some code:

    CudaBlas blas = new CudaBlas(PointerMode.Host);

    float[] data = new float[] { 2, 20, 5, 1, 10 };
    CudaDeviceVariable<float> d_data = data;

    int res = blas.Min(d_data, 1 ); //res = 4

    MessageBox.Show(res.ToString());

    blas.Dispose();
    //again but with device pointers...
    blas = new CudaBlas(PointerMode.Device);
    CudaDeviceVariable<int> d_res = new CudaDeviceVariable<int>(1);
    blas.Min(d_data, 1, d_res);

    res = d_res; //res = 4
    MessageBox.Show(res.ToString());

reveals: FORTRAN-indexing starting at 1, isn't it?

**Comment by mrakgr** [comment]
Er, [yes it does.](https://github.com/kunzmi/managedCuda/issues/6) Memory is a fickle thing. Once again, sorry about that.

**Pull request closed without merging**
